=== cre-dev/xml2db/tests/sample_models/orders/orders.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:bt="http://www.cre.fr/xml2db/base_types.xsd">
    <xs:import schemaLocation="base_types.xsd"
                namespace="http://www.cre.fr/xml2db/base_types.xsd" />
    <xs:complexType name="companyIdType">
        <xs:choice>
            <xs:element name="ace" type="bt:stringtype"/>
            <xs:element name="bic" type="bt:stringtype"/>
            <xs:element name="lei" type="bt:stringtype"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="ZipCodeType">
        <xs:simpleContent>
            <xs:extension base="bt:PostalCodeType">
                <xs:attribute name="state" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="Extra">
        <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="contacttype">
        <xs:sequence>
            <xs:element name="name" type="bt:stringtype"/>
            <xs:element name="address" type="bt:stringtype"/>
            <xs:element name="city" type="bt:stringtype"/>
            <xs:element name="zip" type="ZipCodeType"/>
            <xs:element name="country" type="bt:stringtype"/>
            <xs:element name="phoneNumber" type="bt:stringtype" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="companyId" type="companyIdType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="coordinates" type="bt:CoordinatesListType" minOccurs="0"/>
            <xs:element name="extra" type="Extra" minOccurs="0"/>
            <xs:element name="a_very_long_field_type_that_makes_col_name_exceeds_max_identifier_length" type="bt:stringtype" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="intfeaturetype">
        <xs:sequence>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="value" type="bt:inttype"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stringfeaturetype">
        <xs:sequence>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="value" type="bt:stringtype"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="productfeaturestype">
        <xs:sequence maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="unbounded" name="intfeature_with_peculiarly_long_suffix_which_overflow_max_length" type="intfeaturetype"/>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="stringfeature" type="stringfeaturetype"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="producttype">
        <xs:sequence>
            <xs:element name="name" type="bt:stringtype"/>
            <xs:element name="version" type="bt:stringtype"/>
            <xs:element name="features" type="productfeaturestype" minOccurs="0"/>
            <xs:element name="related_product" type="producttype" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- deliveryType tests the case where the same element name and complex type appear
         in two branches of a xs:choice (sequence branch and standalone branch) -->
    <xs:complexType name="deliveryType">
        <xs:choice>
            <xs:sequence>
                <xs:element name="from" type="contacttype"/>
                <xs:element name="to" type="contacttype"/>
            </xs:sequence>
            <xs:element name="to" type="contacttype"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="itemtype">
        <xs:sequence>
            <xs:element name="product" type="producttype" minOccurs="1" maxOccurs="1"/>
            <xs:element name="note" type="bt:stringtype" minOccurs="0"/>
            <xs:element name="comment" type="bt:stringtype" minOccurs="0"/>
            <xs:element name="quantity" type="bt:quantitytype"/>
            <xs:element name="price" type="bt:dectype"/>
            <xs:element name="currency" type="bt:currencytype"/>
            <xs:element name="delivery" type="deliveryType" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="shipordertype">
        <xs:sequence>
            <xs:element name="orderperson" type="contacttype" minOccurs="1" maxOccurs="1"/>
            <xs:element name="shipto" type="contacttype" minOccurs="0" maxOccurs="1"/>
            <xs:element name="item" maxOccurs="unbounded" type="itemtype"/>
        </xs:sequence>
        <xs:attribute name="orderid" type="bt:stringtype" use="required" />
        <xs:attribute name="processed_at" type="xs:dateTime" />
    </xs:complexType>

    <xs:complexType name="orderstype">
        <xs:sequence>
            <xs:element name="version" type="bt:versiontype" />
            <xs:element name="shiporder" type="shipordertype" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="batch_id" type="bt:stringtype" />
    </xs:complexType>

    <xs:element name="orders" type="orderstype"/>

</xs:schema>

=== cre-dev/xml2db/tests/sample_models/orders/xml/order3.xml
<?xml version='1.0' encoding='utf-8'?>
<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" batch_id="4" xsi:noNamespaceSchemaLocation="../orders.xsd">
  <version>2</version>
  <shiporder orderid="3" processed_at="2023-09-11T18:27:56.000+02:00">
    <orderperson name="billing">
      <name>Alice</name>
      <address>string</address>
      <city>string</city>
      <zip codingSystem="int">21093</zip>
      <country>US</country>
    </orderperson>
    <shipto name="shipping">
      <name>Bob</name>
      <address>string</address>
      <city>string</city>
      <zip codingSystem="us">102832</zip>
      <country>FR</country>
      <phoneNumber>+1732897354</phoneNumber>
      <phoneNumber>+1732323984</phoneNumber>
      <companyId>
        <bic>JIDAZIO786DAZH</bic>
      </companyId>
      <coordinates>48.87271337163929 2.323433844198471</coordinates>
      <a_very_long_field_type_that_makes_col_name_exceeds_max_identifier_length>test</a_very_long_field_type_that_makes_col_name_exceeds_max_identifier_length>
    </shipto>
    <item>
      <product>
        <name>product 1</name>
        <version>premium</version>
      </product>
      <quantity>10</quantity>
      <price>12.3</price>
      <currency>EUR</currency>
    </item>
    <item>
      <product>
        <name>product 1</name>
        <version>premium</version>
      </product>
      <note>string</note>
      <quantity>21</quantity>
      <price>70.4</price>
      <currency>EUR</currency>
    </item>
  </shiporder>
</orders>

=== cre-dev/xml2db/tests/sample_models/orders/xml/order2.xml
<?xml version='1.0' encoding='utf-8'?>
<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" batch_id="2" xsi:noNamespaceSchemaLocation="../orders.xsd">
  <version>2</version>
  <shiporder orderid="2" processed_at="2023-09-10T09:39:45.000+02:00">
    <orderperson>
      <name>Alice</name>
      <address>string</address>
      <city>string</city>
      <zip codingSystem="int">21093</zip>
      <country>string</country>
      <companyId>
        <lei>198210983210983HE1209</lei>
      </companyId>
    </orderperson>
    <item>
      <product>
        <name>product 2</name>
        <version>regular</version>
      </product>
      <quantity>43</quantity>
      <price>30.3</price>
      <currency>EUR</currency>
    </item>
    <item>
      <product>
        <name>product 3</name>
        <version>regular</version>
      </product>
      <note>string</note>
      <quantity>21</quantity>
      <price>70.4</price>
      <currency>EUR</currency>
    </item>
    <item>
      <product>
        <name>product 1</name>
        <version>premium</version>
      </product>
      <quantity>2</quantity>
      <price>12.2</price>
      <currency>EUR</currency>
    </item>
  </shiporder>
</orders>

=== cre-dev/xml2db/tests/sample_models/orders/xml/order1.xml
<?xml version='1.0' encoding='utf-8'?>
<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" batch_id="5" xsi:noNamespaceSchemaLocation="../orders.xsd">
  <version>2</version>
  <shiporder orderid="1" processed_at="2023-09-10T09:37:00.000+02:00">
    <orderperson name="billing">
      <name>Bob</name>
      <address>string</address>
      <city>string</city>
      <zip codingSystem="us">102832</zip>
      <country>FR</country>
      <phoneNumber>+1732897354</phoneNumber>
      <phoneNumber>+1732323984</phoneNumber>
      <companyId>
        <bic>JIDAZIO786DAZH</bic>
      </companyId>
    </orderperson>
    <item>
      <product>
        <name>product 1</name>
        <version>regular</version>
        <features>
          <intfeature_with_peculiarly_long_suffix_which_overflow_max_length>
            <id>length</id>
            <value>60</value>
          </intfeature_with_peculiarly_long_suffix_which_overflow_max_length>
          <intfeature_with_peculiarly_long_suffix_which_overflow_max_length>
            <id>width</id>
            <value>40</value>
          </intfeature_with_peculiarly_long_suffix_which_overflow_max_length>
          <intfeature_with_peculiarly_long_suffix_which_overflow_max_length>
            <id>weight</id>
            <value>10</value>
          </intfeature_with_peculiarly_long_suffix_which_overflow_max_length>
          <stringfeature>
            <id>color</id>
            <value>red</value>
          </stringfeature>
        </features>
      </product>
      <quantity>13</quantity>
      <price>340.23</price>
      <currency>EUR</currency>
    </item>
    <item>
      <product>
        <name>product 2</name>
        <version>regular</version>
      </product>
      <note>string</note>
      <quantity>8</quantity>
      <price>56.2</price>
      <currency>EUR</currency>
    </item>
    <item>
      <product>
        <name>product 1</name>
        <version>premium</version>
      </product>
      <quantity>25</quantity>
      <price>21.7</price>
      <currency>EUR</currency>
    </item>
  </shiporder>
</orders>

=== cre-dev/xml2db/tests/sample_models/orders/equivalent_xml/order1a.xml
<?xml version='1.0' encoding='utf-8'?>
<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" batch_id="5" xsi:noNamespaceSchemaLocation="../orders.xsd">
  <version>2</version>
  <shiporder orderid="1" processed_at="2023-09-10T09:37:00.000+02:00  ">
    <orderperson name="billing">
      <name>    Bob    </name>
      <address>string</address>
      <city>string</city>
      <zip codingSystem="us">102832</zip>
      <country>FR</country>
      <phoneNumber>+1732897354</phoneNumber>
      <phoneNumber>+1732323984</phoneNumber>
      <companyId>
        <bic>JIDAZIO786DAZH</bic>
      </companyId>
      <extra>
        <profileName>profile 1</profileName>
      </extra>
    </orderperson>
    <item>
      <product>
        <name>
          product 1
        </name>
        <version>regular</version>
        <related_product>
          <name>
            product 1
          </name>
          <version>premium</version>
        </related_product>
        <related_product>
          <name>
            product 1
          </name>
          <version>basic</version>
        </related_product>
      </product>
      <quantity>13</quantity>
      <price>
        340.23
      </price>
      <currency>EUR</currency>
    </item>
    <item>
      <product>
        <name>product 2</name>
        <version>regular</version>
      </product>
      <note>string</note>
      <comment>this comment should be skipped</comment>
      <quantity>8</quantity>
      <price>56.2</price>
      <currency>EUR</currency>
    </item>
    <item>
      <product>
        <name>product 1</name>
        <version>premium</version>
      </product>
      <quantity>  25</quantity>
      <price>21.7</price>
      <currency>EUR</currency>
    </item>
  </shiporder>
</orders>
